version: "3.9"

# Development configuration with full ingestion
include:
  - docker-compose.base.yml

services:
  # Add the ingestion worker for development
  ingest-worker:
    build: ./backend
    command: python ingest.py
    environment:
      - MANIFEST_DIR=/data/manifests
      - COLLECTION_NAME=telerik_blazor_docs
      - QDRANT_URL=qdrant:6333
      # - EMBED_MODEL=BAAI/bge-large-en-v1.5
      - EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - WINDOW_SIZE=400
      - WINDOW_OVERLAP=50
    volumes:
      - ./data:/data
    depends_on:
      - qdrant
