version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.9.4
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  rag-api:
    build: ./backend
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - QDRANT_URL=qdrant:6333
      - OLLAMA_HOST=http://ollama:11434
      - COLLECTION_NAME=telerik_blazor_docs
    depends_on:
      - qdrant
      - ollama
    ports:
      - "8000:8000"

  ingest-worker:
    build: ./backend
    command: python ingest.py
    environment:
      - MANIFEST_DIR=/data/manifests
      - COLLECTION_NAME=telerik_blazor_docs
      - QDRANT_URL=qdrant:6333
      # - EMBED_MODEL=BAAI/bge-large-en-v1.5
      - EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - WINDOW_SIZE=400
      - WINDOW_OVERLAP=50
    volumes:
      - ./data:/data
    depends_on:
      - qdrant

  frontend:
    build: ./frontend
    depends_on:
      - rag-api
    ports:
      - "3000:80"

volumes:
  qdrant_storage:
  ollama_data:
