# Base configuration with core services
services:
  qdrant:
    image: qdrant/qdrant:v1.9.4
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD", "sh", "-c", "timeout 3 bash -c '</dev/tcp/localhost/6333'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  rag-api:
    build: ./backend
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - QDRANT_URL=qdrant:6333
      - OLLAMA_HOST=http://ollama:11434
      - COLLECTION_NAME=telerik_blazor_docs
    depends_on:
      - qdrant
      - ollama
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - rag-api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_CHAT_API_URL=http://localhost:8000/v1/chat

volumes:
  qdrant_storage:
  ollama_data:
